version: '3'
services:
  # The main django app that responds to web requests
  hnsxplorer:
    image: hnsxplorer
    ports: ['8000:8000']
    build: .
    entrypoint: python manage.py runserver 0.0.0.0:8000
    environment:
      - 'DEBUG=1'
    volumes:
      - ./hsdexplorer/:/app/
    env_file:
      - local.env
    depends_on:
      - postgres.infra
      - migration
      - redis
      - handshake-node

  # A background worker that processes new blocks and saves information about
  # them to a postgres database
  hnsxplorer-celery:
    image: hnsxplorer
    build: .
    entrypoint: ["celery", "-A", "hsdexplorer", "worker", "-l", "info", "-B"]
    depends_on:
      - redis

  postgres.infra:
    image: postgres:10.5
    environment:
      - 'POSTGRES_USER=hnsxplorer_testnet'
      - 'POSTGRES_DB=hnsxplorer_testnet'

  # Caching + celery queue
  redis:
    image: redis

  # A forked copy of handshakes hsd node that includes a few open prs against
  # the hsd project
  handshake-node:
    image: tdickman/hsd:testnet4-stable
    ports: ['13037:13037']
    command: ["hsd", "--index-address=true", "--index-tx=true", "--http-host=0.0.0.0", "--no-auth", "--log-level=info"]

  # Runs db migrations at startup
  migration:
    image: hnsxplorer
    entrypoint: python manage.py migrate
