apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/hello-world-392/handshake-explorer
    context: .
deploy:
  kubectl:
    manifests:
    - ./kube/*.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      projectId: hello-world-392
