apiVersion: v1
kind: Service
metadata:
  name: handshake-node
spec:
  ports:
    - port: 13037
      targetPort: 13037
  selector:
    app: handshake-node
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: handshake-node
  name: handshake-node
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: handshake-node
  template:
    metadata:
      labels:
        app: handshake-node
    spec:
      containers:
        - image: tdickman/hsd:testnet4-stable
          name: handshake-node
          command: ["hsd", "--index-address=true", "--index-tx=true", "--http-host=0.0.0.0", "--no-auth"]
          volumeMounts:
            - mountPath: /root/.hsd
              name: hsd-data
      restartPolicy: Always
      volumes:
        - name: hsd-data
          persistentVolumeClaim:
            claimName: hsd-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsd-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd
