# Required variables:
# - GCLOUD_SERVICE_KEY - a Gcloud service key with permission to push docker
# containers to the docker registry, and to deploy to k8s.
version: 2
jobs:
  build_deploy:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      - run:
          name: Push application Docker image
          command: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
            chmod +x skaffold
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud auth configure-docker --quiet
            gcloud config set compute/zone us-central1-a
            gcloud config set project hello-world-392
            gcloud container clusters get-credentials main
            ./skaffold build -p gcb
      - deploy:
          name: Deploy image to GCloud
          command: ./skaffold deploy -p gcb
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
               - master
